services:
  # Backend API Service
  - type: web
    name: film-rental-backend
    runtime: native
    plan: free
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar backend/target/Film_Rental_System-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: PORT
        value: 8082
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false

  # Frontend UI Service
  - type: web
    name: film-rental-frontend
    runtime: native
    plan: free
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar frontend/target/frontend-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: PORT
        value: 8081
      - key: BACKEND_URL
        value: https://film-rental-backend.onrender.com/api
